"""add google auth fields to users

Revision ID: 236ccb85b029
Revises: b58c4f7d2e91
Create Date: 2026-05-21 14:52:07.692397
"""
from __future__ import annotations

from alembic import op
import sqlalchemy as sa



# revision identifiers, used by Alembic.
revision = '236ccb85b029'
down_revision = 'b58c4f7d2e91'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("users", sa.Column("auth_provider", sa.String(length=30), nullable=False, server_default="manual",))
    op.add_column("users", sa.Column("google_sub", sa.String(length=255), nullable=True))
    op.add_column("users", sa.Column("profile_picture_url", sa.String(length=500), nullable=True))
    op.add_column("users", sa.Column("email_verified", sa.Boolean(), nullable=False, server_default=sa.false(),))
    op.alter_column("users", "password_hash", existing_type=sa.TEXT(), nullable=True)
    op.create_index(op.f("ix_users_users_auth_provider"), "users", ["auth_provider"], unique=False)
    op.create_index(op.f("ix_users_users_google_sub"), "users", ["google_sub"], unique=True)
    op.create_check_constraint("auth_provider_valid_check", "users", "auth_provider IN ('manual', 'google')")
    op.create_check_constraint("manual_users_password_required_check", "users", "(auth_provider != 'manual') OR (password_hash IS NOT NULL)")
    op.alter_column("users", "auth_provider", server_default=None)
    op.alter_column("users", "email_verified", server_default=None)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(
        "manual_users_password_required_check",
        "users",
        type_="check",
    )

    op.drop_constraint(
        "auth_provider_valid_check",
        "users",
        type_="check",
    )

    op.drop_index(
        op.f("ix_users_users_google_sub"),
        table_name="users",
    )

    op.drop_index(
        op.f("ix_users_users_auth_provider"),
        table_name="users",
    )

    op.alter_column(
        "users",
        "password_hash",
        existing_type=sa.TEXT(),
        nullable=False,
    )

    op.drop_column("users", "email_verified")
    op.drop_column("users", "profile_picture_url")
    op.drop_column("users", "google_sub")
    op.drop_column("users", "auth_provider")
    # ### end Alembic commands ###
