"""initial schema

Revision ID: 3bd016ede9f5
Revises: 
Create Date: 2026-05-06 11:46:38.571028
"""
from __future__ import annotations

from alembic import op
import sqlalchemy as sa



# revision identifiers, used by Alembic.
revision = '3bd016ede9f5'
down_revision = None
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('users',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('full_name', sa.String(length=150), nullable=False),
    sa.Column('email', sa.String(length=255), nullable=False),
    sa.Column('password_hash', sa.Text(), nullable=False),
    sa.Column('role', sa.String(length=30), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.CheckConstraint("email ~* '^[A-Za-z0-9._%+-]+@[A-Za-z0-9.-]+\\.[A-Za-z]{2,}$'", name=op.f('ck_users_email_format_check')),
    sa.CheckConstraint('length(trim(full_name)) >= 2', name=op.f('ck_users_full_name_length_check')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_users')),
    sa.UniqueConstraint('email', name=op.f('uq_users_email'))
    )
    op.create_table('documents',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('title', sa.String(length=255), nullable=True),
    sa.Column('original_file_name', sa.String(length=255), nullable=False),
    sa.Column('stored_file_name', sa.String(length=255), nullable=False),
    sa.Column('file_path', sa.Text(), nullable=False),
    sa.Column('file_url', sa.Text(), nullable=True),
    sa.Column('file_type', sa.String(length=30), nullable=False),
    sa.Column('file_size_bytes', sa.BigInteger(), nullable=True),
    sa.Column('total_pages', sa.Integer(), nullable=True),
    sa.Column('status', sa.String(length=30), nullable=False),
    sa.Column('error_message', sa.Text(), nullable=True),
    sa.Column('uploaded_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('processed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.CheckConstraint('file_size_bytes IS NULL OR file_size_bytes >= 0', name=op.f('ck_documents_document_file_size_check')),
    sa.CheckConstraint('length(trim(file_path)) >= 1', name=op.f('ck_documents_document_file_path_check')),
    sa.CheckConstraint('length(trim(original_file_name)) >= 1', name=op.f('ck_documents_document_original_file_name_check')),
    sa.CheckConstraint('length(trim(stored_file_name)) >= 1', name=op.f('ck_documents_document_stored_file_name_check')),
    sa.CheckConstraint('total_pages IS NULL OR total_pages >= 0', name=op.f('ck_documents_document_total_pages_check')),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name=op.f('fk_documents_user_id_users'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_documents'))
    )
    op.create_index(op.f('ix_documents_documents_user_id'), 'documents', ['user_id'], unique=False)
    op.create_table('chat_sessions',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('document_id', sa.UUID(), nullable=False),
    sa.Column('title', sa.String(length=255), nullable=True),
    sa.Column('status', sa.String(length=30), nullable=False),
    sa.Column('started_at', sa.DateTime(), nullable=False),
    sa.Column('last_message_at', sa.DateTime(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.CheckConstraint("status IN ('active', 'closed', 'archived')", name=op.f('ck_chat_sessions_chat_session_status_check')),
    sa.ForeignKeyConstraint(['document_id'], ['documents.id'], name=op.f('fk_chat_sessions_document_id_documents'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name=op.f('fk_chat_sessions_user_id_users'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_chat_sessions'))
    )
    op.create_index(op.f('ix_chat_sessions_chat_sessions_document_id'), 'chat_sessions', ['document_id'], unique=False)
    op.create_index(op.f('ix_chat_sessions_chat_sessions_user_id'), 'chat_sessions', ['user_id'], unique=False)
    op.create_table('document_chunks',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('document_id', sa.UUID(), nullable=False),
    sa.Column('pinecone_vector_id', sa.String(length=255), nullable=False),
    sa.Column('chunk_index', sa.Integer(), nullable=False),
    sa.Column('page_number_start', sa.Integer(), nullable=True),
    sa.Column('page_number_end', sa.Integer(), nullable=True),
    sa.Column('chunk_text', sa.Text(), nullable=False),
    sa.Column('token_count', sa.Integer(), nullable=True),
    sa.Column('embedding_model', sa.String(length=100), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.CheckConstraint('chunk_index >= 0', name=op.f('ck_document_chunks_document_chunk_index_check')),
    sa.CheckConstraint('length(trim(chunk_text)) >= 1', name=op.f('ck_document_chunks_document_chunk_text_check')),
    sa.CheckConstraint('page_number_end IS NULL OR page_number_end >= 1', name=op.f('ck_document_chunks_document_chunk_page_end_check')),
    sa.CheckConstraint('page_number_start IS NULL OR page_number_end IS NULL OR page_number_end >= page_number_start', name=op.f('ck_document_chunks_document_chunk_page_range_check')),
    sa.CheckConstraint('page_number_start IS NULL OR page_number_start >= 1', name=op.f('ck_document_chunks_document_chunk_page_start_check')),
    sa.CheckConstraint('token_count IS NULL OR token_count >= 0', name=op.f('ck_document_chunks_document_chunk_token_count_check')),
    sa.ForeignKeyConstraint(['document_id'], ['documents.id'], name=op.f('fk_document_chunks_document_id_documents'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_document_chunks')),
    sa.UniqueConstraint('document_id', 'chunk_index', name='uq_document_chunks_document_id_chunk_index'),
    sa.UniqueConstraint('pinecone_vector_id', name=op.f('uq_document_chunks_pinecone_vector_id'))
    )
    op.create_index(op.f('ix_document_chunks_document_chunks_document_id'), 'document_chunks', ['document_id'], unique=False)
    op.create_table('document_processing_logs',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('document_id', sa.UUID(), nullable=False),
    sa.Column('step_name', sa.String(length=50), nullable=False),
    sa.Column('status', sa.String(length=30), nullable=False),
    sa.Column('message', sa.Text(), nullable=True),
    sa.Column('started_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('completed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.CheckConstraint("status IN ('pending', 'processing', 'completed', 'failed')", name=op.f('ck_document_processing_logs_document_processing_log_status_check')),
    sa.CheckConstraint('completed_at IS NULL OR started_at IS NULL OR completed_at >= started_at', name=op.f('ck_document_processing_logs_document_processing_log_time_check')),
    sa.CheckConstraint('length(trim(step_name)) >= 1', name=op.f('ck_document_processing_logs_document_processing_log_step_name_check')),
    sa.ForeignKeyConstraint(['document_id'], ['documents.id'], name=op.f('fk_document_processing_logs_document_id_documents'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_document_processing_logs'))
    )
    op.create_index(op.f('ix_document_processing_logs_document_processing_logs_document_id'), 'document_processing_logs', ['document_id'], unique=False)
    op.create_table('chat_messages',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('chat_session_id', sa.UUID(), nullable=False),
    sa.Column('role', sa.String(length=30), nullable=False),
    sa.Column('content', sa.Text(), nullable=False),
    sa.Column('llm_model', sa.String(length=100), nullable=True),
    sa.Column('prompt_tokens', sa.Integer(), nullable=True),
    sa.Column('completion_tokens', sa.Integer(), nullable=True),
    sa.Column('total_tokens', sa.Integer(), nullable=True),
    sa.Column('estimated_cost', sa.Numeric(precision=12, scale=6), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.CheckConstraint("role IN ('user', 'assistant', 'system')", name=op.f('ck_chat_messages_chat_message_role_check')),
    sa.CheckConstraint('completion_tokens IS NULL OR completion_tokens >= 0', name=op.f('ck_chat_messages_chat_message_completion_tokens_check')),
    sa.CheckConstraint('estimated_cost IS NULL OR estimated_cost >= 0', name=op.f('ck_chat_messages_chat_message_estimated_cost_check')),
    sa.CheckConstraint('length(trim(content)) >= 1', name=op.f('ck_chat_messages_chat_message_content_check')),
    sa.CheckConstraint('prompt_tokens IS NULL OR prompt_tokens >= 0', name=op.f('ck_chat_messages_chat_message_prompt_tokens_check')),
    sa.CheckConstraint('total_tokens IS NULL OR total_tokens >= 0', name=op.f('ck_chat_messages_chat_message_total_tokens_check')),
    sa.ForeignKeyConstraint(['chat_session_id'], ['chat_sessions.id'], name=op.f('fk_chat_messages_chat_session_id_chat_sessions'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_chat_messages'))
    )
    op.create_index(op.f('ix_chat_messages_chat_messages_chat_session_id'), 'chat_messages', ['chat_session_id'], unique=False)
    op.create_table('usage_logs',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('document_id', sa.UUID(), nullable=True),
    sa.Column('session_id', sa.UUID(), nullable=True),
    sa.Column('action_type', sa.String(length=50), nullable=False),
    sa.Column('provider', sa.String(length=100), nullable=True),
    sa.Column('model_name', sa.String(length=100), nullable=True),
    sa.Column('input_tokens', sa.Integer(), nullable=True),
    sa.Column('output_tokens', sa.Integer(), nullable=True),
    sa.Column('total_tokens', sa.Integer(), nullable=True),
    sa.Column('cost', sa.Numeric(precision=12, scale=6), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.CheckConstraint('cost IS NULL OR cost >= 0', name=op.f('ck_usage_logs_usage_log_cost_check')),
    sa.CheckConstraint('input_tokens IS NULL OR input_tokens >= 0', name=op.f('ck_usage_logs_usage_log_input_tokens_check')),
    sa.CheckConstraint('length(trim(action_type)) >= 1', name=op.f('ck_usage_logs_usage_log_action_type_check')),
    sa.CheckConstraint('output_tokens IS NULL OR output_tokens >= 0', name=op.f('ck_usage_logs_usage_log_output_tokens_check')),
    sa.CheckConstraint('total_tokens IS NULL OR total_tokens >= 0', name=op.f('ck_usage_logs_usage_log_total_tokens_check')),
    sa.ForeignKeyConstraint(['document_id'], ['documents.id'], name=op.f('fk_usage_logs_document_id_documents'), ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['session_id'], ['chat_sessions.id'], name=op.f('fk_usage_logs_session_id_chat_sessions'), ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name=op.f('fk_usage_logs_user_id_users'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_usage_logs'))
    )
    op.create_index(op.f('ix_usage_logs_usage_logs_document_id'), 'usage_logs', ['document_id'], unique=False)
    op.create_index(op.f('ix_usage_logs_usage_logs_session_id'), 'usage_logs', ['session_id'], unique=False)
    op.create_index(op.f('ix_usage_logs_usage_logs_user_id'), 'usage_logs', ['user_id'], unique=False)
    op.create_table('message_sources',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('message_id', sa.UUID(), nullable=False),
    sa.Column('chunk_id', sa.UUID(), nullable=False),
    sa.Column('source_rank', sa.Integer(), nullable=True),
    sa.Column('similarity_score', sa.Float(), nullable=True),
    sa.Column('page_number_start', sa.Integer(), nullable=True),
    sa.Column('page_number_end', sa.Integer(), nullable=True),
    sa.Column('quoted_text', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.CheckConstraint('page_number_end IS NULL OR page_number_end >= 1', name=op.f('ck_message_sources_message_source_page_end_check')),
    sa.CheckConstraint('page_number_start IS NULL OR page_number_end IS NULL OR page_number_end >= page_number_start', name=op.f('ck_message_sources_message_source_page_range_check')),
    sa.CheckConstraint('page_number_start IS NULL OR page_number_start >= 1', name=op.f('ck_message_sources_message_source_page_start_check')),
    sa.CheckConstraint('similarity_score IS NULL OR (similarity_score >= 0 AND similarity_score <= 1)', name=op.f('ck_message_sources_message_source_similarity_score_check')),
    sa.CheckConstraint('source_rank IS NULL OR source_rank >= 1', name=op.f('ck_message_sources_message_source_rank_check')),
    sa.ForeignKeyConstraint(['chunk_id'], ['document_chunks.id'], name=op.f('fk_message_sources_chunk_id_document_chunks'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['message_id'], ['chat_messages.id'], name=op.f('fk_message_sources_message_id_chat_messages'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_message_sources')),
    sa.UniqueConstraint('message_id', 'chunk_id', name='uq_message_sources_message_id_chunk_id')
    )
    op.create_index(op.f('ix_message_sources_message_sources_chunk_id'), 'message_sources', ['chunk_id'], unique=False)
    op.create_index(op.f('ix_message_sources_message_sources_message_id'), 'message_sources', ['message_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_message_sources_message_sources_message_id'), table_name='message_sources')
    op.drop_index(op.f('ix_message_sources_message_sources_chunk_id'), table_name='message_sources')
    op.drop_table('message_sources')
    op.drop_index(op.f('ix_usage_logs_usage_logs_user_id'), table_name='usage_logs')
    op.drop_index(op.f('ix_usage_logs_usage_logs_session_id'), table_name='usage_logs')
    op.drop_index(op.f('ix_usage_logs_usage_logs_document_id'), table_name='usage_logs')
    op.drop_table('usage_logs')
    op.drop_index(op.f('ix_chat_messages_chat_messages_chat_session_id'), table_name='chat_messages')
    op.drop_table('chat_messages')
    op.drop_index(op.f('ix_document_processing_logs_document_processing_logs_document_id'), table_name='document_processing_logs')
    op.drop_table('document_processing_logs')
    op.drop_index(op.f('ix_document_chunks_document_chunks_document_id'), table_name='document_chunks')
    op.drop_table('document_chunks')
    op.drop_index(op.f('ix_chat_sessions_chat_sessions_user_id'), table_name='chat_sessions')
    op.drop_index(op.f('ix_chat_sessions_chat_sessions_document_id'), table_name='chat_sessions')
    op.drop_table('chat_sessions')
    op.drop_index(op.f('ix_documents_documents_user_id'), table_name='documents')
    op.drop_table('documents')
    op.drop_table('users')
    # ### end Alembic commands ###
